context:
  version: 6.0.12.30
  build_number: '0'

package:
  name: ob-metaflow-stubs
  version: ${{ version }}

source:
  - url: https://pypi.io/packages/source/o/ob-metaflow-stubs/ob_metaflow_stubs-${{ version }}.tar.gz
    sha256: f77dd41841f86b78e6b5fc499665dfe5ae774c8d59e967c55de91340b18dbe98

build:
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

about:
  summary: Metaflow stubs for Outerbounds
  license: Apache-2.0
