[workspace]
name = "pixi"
channels = ["https://repo.anaconda.com/pkgs/main"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "win-64"]

[dependencies]
# renovate: datasource=conda depName=main/pixi
pixi = "==0.70.2"
