package:
  name: ana-cli
  version: ${{ env.get("PKG_VERSION") | default("0.0.0") }}

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - rust
    - if: linux
      then:
        - pkg-config
  host:
    - if: linux
      then:
        - openssl

tests:
  - script:
      - if: unix
        then: run_test.sh
      - if: win
        then: run_test.bat

about:
  homepage: https://github.com/anaconda/ana-cli
  license: Apache-2.0
  summary: A Single Entry Point for Data Science, ML, & AI-powered Applications
