package:
  name: ana-cli
  # TODO: Automatically generate version number
  version: 0.1.0

source:
  path: ..

build:
  number: 0
  script:
    - cargo build --release
    - mkdir -p $PREFIX/bin
    - cp target/release/ana $PREFIX/bin/

requirements:
  build:
    - rust

tests:
  - script:
      - ana
      - |
        expected="Hello, world!"
        actual="$(ana)"
        if [ "$actual" != "$expected" ]; then
          echo "FAIL: Output mismatch"
          echo "  Expected: $expected"
          echo "  Actual:   $actual"
          exit 1
        fi

about:
  homepage: https://github.com/anaconda/ana-cli
  license: Apache-2.0
  summary: A Single Entry Point for Data Science, ML, & AI-powered Applications
