package:
  name: anaconda-cli
  version: ${{ env.get("PKG_VERSION") | default("0.0.0") }}

source:
  path: ..

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p .cargo
        - echo '[net]' > .cargo/config.toml
        - echo 'git-fetch-with-cli = true' >> .cargo/config.toml
        - git config --global url."https://x-access-token:${{ env.get("GITHUB_TOKEN", default="") }}@github.com/".insteadOf "https://github.com/"
        - cargo build --release --no-default-features --features conda-package
        - mkdir -p $PREFIX/bin
        - cp target/release/ana $PREFIX/bin/
    - if: win
      then:
        - if not exist .cargo mkdir .cargo
        - echo [net] > .cargo\config.toml
        - echo git-fetch-with-cli = true >> .cargo\config.toml
        - cargo build --release --no-default-features --features conda-package
        - if not exist %PREFIX%\Library\bin mkdir %PREFIX%\Library\bin
        - copy target\release\ana.exe %PREFIX%\Library\bin\ana.exe

requirements:
  build:
    - rust
    - git
  run:
    - anaconda-client

about:
  homepage: https://github.com/anaconda/ana-cli
  license: Apache-2.0
  summary: A Single Entry Point for Data Science, ML, & AI-powered Applications
