name: Auto-label PR

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply conventional commit labels
        uses: bcoe/conventional-release-labels@v1
        with:
          ignored_types: "['build']"
