name: pre-commit

on:
  # Caches have a certain level of isolation, see https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  # We run on push to main to have all caches in the main branch so that they can be reused for PRs.
  push:
    branches:
      - main
  merge_group:
  pull_request:
    # Default is [opened, reopened, synchronize]. Since we want to run pre-commit on "ready to review",
    # we add that one. Since lists are overwritten, not merged, we add all four.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    # for documentation of the default behaviour
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

# Cancel a previous job if the same workflow is triggers on the same PR or commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on:
      labels:
        - ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.ANACONDA_BOT_TOKEN }}

      - name: Configure git for private repos
        run: |
          git config --global url."https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          pixi-version: v0.66.0

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ runner.arch }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit and locks
        id: updates
        run: |
          echo "::group::Rebuilding lockfiles and running pre-commit"
          pixi lock
          pixi run cargo-lock
          pixi run pre-commit || :
          echo "::endgroup::"
          echo ""
          if git status --porcelain | grep .; then
            echo "::error::Changes detected:"
            if git status --porcelain | grep Cargo.lock; then echo "- Cargo.lock"; fi
            if git status --porcelain | grep pixi.lock; then echo "- pixi.lock"; fi
            if git status --porcelain | grep -vE "(Cargo|pixi).lock"; then echo "- Pre-commit updates"; fi
            echo "changed=1" >>$GITHUB_OUTPUT
          else
            echo "No changes detected!"
          fi

      - name: Checkout the branch we're running on to enable a commit to it
        if: steps.updates.outputs.changed == 1
        run: |
          git fetch origin refs/heads/${{ github.head_ref }}:refs/remotes/origin/${{ github.head_ref }}
          git checkout ${{ github.head_ref }}

      - name: Commit linted files
        if: steps.updates.outputs.changed == 1
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        with:
          message: 'chore(pre-commit): Linting'
          author_name: Anaconda Bot
          author_email: devops+anaconda-bot@anaconda.com

      - name: Fail if changes occurred
        if: steps.updates.outputs.changed == 1
        run: |
          echo "::error::Changes were committed. A new CI run will start."
          exit 1
